-- 코드를 입력하세요
SELECT CAST(SUBSTRING(DATETIME, 12, 2) as UNSIGNED) as HOUR, COUNT(*) as COUNT
FROM ANIMAL_OUTS
WHERE SUBSTRING(DATETIME, 12, 2) >= '09' and SUBSTRING(DATETIME, 12, 2) <= '19'
GROUP BY SUBSTRING(DATETIME, 12, 2)
ORDER BY HOUR
;