SELECT fi.ID, fn.FISH_NAME, fi.LENGTH
FROM FISH_INFO as fi
JOIN FISH_NAME_INFO as fn
ON fi.FISH_TYPE = fn.FISH_TYPE
WHERE fi.FISH_TYPE in (
    SELECT FISH_TYPE
    FROM FISH_INFO
    GROUP BY FISH_TYPE
    HAVING LENGTH = MAX(LENGTH)
)
;