SELECT fi.ID, fn.FISH_NAME, fi.LENGTH
FROM FISH_INFO as fi
JOIN FISH_NAME_INFO as fn
ON fi.FISH_TYPE = fn.FISH_TYPE
WHERE (fi.FISH_TYPE, fi.LENGTH) in (
    SELECT FISH_TYPE, MAX(LENGTH)
    FROM FISH_INFO
    GROUP BY FISH_TYPE
)
;