SELECT b.CATEGORY, SUM(bs.SALES) as TOTAL_SALES
FROM BOOK_SALES as bs JOIN BOOK as b ON bs.BOOK_ID = b.BOOK_ID
WHERE SUBSTRING(bs.SALES_DATE, 1, 7) = "2022-01"
GROUP BY b.CATEGORY
ORDER BY b.CATEGORY
;